export default [
  {name: 'AccorHotels', hotels: ['Mercure', 'Novotel', 'Sofitel', 'Fairmont']},
  {name: 'AmericInn', hotels: ['AmericInn']},
  {name: 'Best Western Hotels', hotels: ['Best Western', 'Best Western Plus']},
  {name: 'Carlson Rezidor Hotel Group', hotels: ['Country Inns & Suites', 'Radisson', 'Park Plaza', 'Park Inn']},
  {name: 'Choice Hotels', hotels: ['Comfort Inn', 'Comfort Suites', 'Clarion Inn', 'Clarion Hotel','Quality Inn', 'Econo Lodge', 'Rodeway Inn', 'Sleep Inn', 'Cambria Suites', 'Suburban Extended Stay Hotel', 'Mainstay Suites']},
  {name: 'Drury Hotels', hotels: ['Drury Inn and Suites', 'Pear Tree Inn']},
  {name: 'Extended Stay America Inc', hotels: ['Extended Stay America']},
  {name: 'Four Seasons Hotels and Resorts', hotels: ['Four Seasons Hotels']},
  {name: 'Hilton Worldwide', hotels: ['Hilton', 'Hilton Garden Inn', 'Hampton', 'DoubleTree', 'Home2 Suites', 'Embassy Suites', 'Homewood Suites', 'Waldorf Astoria']},
  {name: 'Hyatt Hotels Corporation', hotels: ['Hyatt', 'Hyatt Place', 'Hyatt Regency', 'Grand Hyatt', 'Andaz']},
  {name: 'InterContinental Hotels Group (IHG)', hotels: ['Holiday Inn', 'Holiday Inn Express', 'Crowne Plaza', 'InterContinental', 'Candlewood Suites', 'Hotel Indigo', 'Staybridge Suites']},
  {name: 'La Quinta Inns & Suites', hotels: ['La Quinta Inn & Suites']},
  {name: 'Marriott International', hotels: ['Marriott', 'Fairfield Inn', 'Courtyard', 'SpringHill Suites', 'TownePlace Suites', 'Residence Inn', 'Sheraton', 'Four Points', 'Aloft Hotels', 'Renaissance Hotels', 'Autograph Collection', 'Gaylord Hotels', 'W Hotels', 'Design Hotels', 'Westin Hotels & Resorts', 'Le Méridien', 'AC Hotels', 'Tribute Portfolio', 'Ritz-Carlton', 'Bulgari Hotels', 'JW Marriott Hotels', 'St. Regis']},
  {name: 'Motel 6', hotels: ['Motel 6', 'Studio 6']},
  {name: 'Omni Hotels & Resorts', hotels: ['Omni Hotels & Resorts']},
  {name: 'Shilo Inns', hotels: ['Shilo Inns']},
  {name: 'Red Lion', hotels: ['Red Lion Inn & Suites', 'Americas Best Value Inn', 'Canadas Best Value Inn', 'Country Hearth Inn & Suites', 'Signature Inn', 'Settle Inn', 'Guest House', 'Lexington', 'Jameson Inn']},
  {name: 'Wyndham Worldwide', hotels: ['Days Inn', 'Super 8', 'Travelodge', 'Knights Inn', 'Microtel Inn & Suites', 'Howard Johnson\'s', 'Baymont Inn & Suites', 'Ramada Plaza', 'Wyndham Garden', 'Hawthorn Suites', 'Wingate', 'Ramada', 'Wyndham', 'Wyndham Grand']}
]
